export const MAP_CENTER = 'MAP_CENTER';
export const MAP_LOADING = 'MAP_LOADING';
export const MAP_TYPE = 'MAP_TYPE';
export const DRAWING_MODE = 'DRAWING_MODE';
export const HIGHLIGHT_LOCALITIES = 'HIGHLIGHT_LOCALITIES';
export const AREAS_LAYER = 'AREAS_LAYER';
export const FIELDS_LAYER = 'FIELDS_LAYER';
export const MY_AREAS_FILTER = 'MY_AREAS_FILTER';
