module.exports = {
  INVITE_USER: 'INVITE_USER',
  ALL_RIGHT: 'ALL_RIGHT',
  UPLOAD_FILES: 'UPLOAD_FILES',

  EDIT_ACCOUNT: 'EDIT_ACCOUNT',

  VIEW_ORGANIZATIONS: 'VIEW_ORGANIZATIONS',
  EDIT_ORGANIZATIONS: 'EDIT_ORGANIZATIONS',

  EDIT_AREAS: 'EDIT_AREAS',
  VIEW_AREAS: 'VIEW_AREAS',

  EDIT_LOCALITIES: 'EDIT_LOCALITIES',
  VIEW_LOCALITIES: 'VIEW_LOCALITIES',

  EDIT_LANDLORDS: 'EDIT_LANDLORDS',
  VIEW_LANDLORDS: 'VIEW_LANDLORDS',

  EDIT_DEPARTMENTS: 'EDIT_DEPARTMENTS',
  VIEW_DEPARTMENTS: 'VIEW_DEPARTMENTS',

  VIEW_FIELDS: 'VIEW_FIELDS',
  EDIT_FIELDS: 'EDIT_FIELDS',

  VIEW_CONTRACTS: 'VIEW_CONTRACTS',
  EDIT_CONTRACTS: 'EDIT_CONTRACTS',

  VIEW_RENTERS: 'VIEW_RENTERS',
  EDIT_RENTERS: 'EDIT_RENTERS',

  EDIT_EXCHANGE_ACTS: 'EDIT_EXCHANGE_ACTS',
  VIEW_EXCHANGE_ACTS: 'VIEW_EXCHANGE_ACTS',
};
