export const INIT_DEPARTMENTS = 'INIT_DEPARTMENTS';
export const PUSH_DEPARTMENT = 'PUSH_DEPARTMENT';
export const REMOVE_DEPARTMENT = 'REMOVE_DEPARTMENT';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const INIT_LOCALITIES = 'INIT_LOCALITIES';
export const CHANGE_ACTIVE_LOCALITY = 'CHANGE_ACTIVE_LOCALITY';
